### PR TITLE
Adding strict DI option to the bootstrap method - 🐙

### LINKED ISSUE #28: You cannot enable StrictDI mode
Angular 1.x supports a Strict Dependency Injection Mode. Enabling it turns off automatic function annotation (useful for preventing minification bugs)

### PR DESCRIPTION
**Pull request by TheMcMurder**
One option to fix #28

### CODE REVIEW

**Comment by TheMcMurder** [comment]
@joeldenning @blittle this is one option to add [StrictDI mode ](https://docs.angularjs.org/api/ng/function/angular.bootstrap#usage)

**Comment by joeldenning** [comment]
Thanks for reporting and fixing this issue. Looking at the angular docs that you linked to, it seems like `strictDI` is the only option in the optional bootstrap config??? Not sure if that's likely to change or not.

Which way would you prefer fixing it?

**Comment by TheMcMurder** [comment]
I'm not sure which way is best. I believe the `bootstrap config` is unlikely to change given angular's maturity. I'm leaning a bit towards #29 

It's probably fine to include it as an option and manage it internally. The only risk is if the config changes that puts the burden on the library rather than the user of the library. I prefer a simple API so I'm really conflicted.

Pros of utilizing Options: 
- Simple API
- Invisible change

Con:
- Manually managing the config object in the library

**Comment by joeldenning** [comment]
I think I lean a little bit towards #29 too. I doubt that it will ever change now that angular 1 is on deprecation path because of angular 2. And so it might be easiest just to keep the API simple.

Closing this in favor of #29

**Pull request closed without merging**
